### PR TITLE
Create test and do the implementation for calculate_final_grade

### PR DESCRIPTION
**Pull request by tdkhanhvu**

### CODE REVIEW

**Review by jraza19 — COMMENTED** [review]
Great work! @tdkhanhvu - when I ran your tests - all of them pass. I have two comments - please ensure that you are calling devtools::document() to keep in check of how things are going.  When I ran this - I got a couple of errors below. 

For error number 1 - the pipe also needs to be imported in from somewhere - [see post here](https://stackoverflow.com/questions/63136204/no-visible-global-function-definition-for)

For error number 2 - i would try adding .data$variable - this makes sure that R know that these are global variables - see option heading "A note on [tidyverse"](https://www.r-bloggers.com/2019/08/no-visible-binding-for-global-variable/). 

The last error is Yanhua's error so no need to worry for you.

image

**Comment by tdkhanhvu** [comment]
It's weird that I run both commands on my RStudio and it does not give the above errors.

How did you run those commands?

image

**Comment by jraza19** [comment]
> It's weird that I run both commands on my RStudio and it does not give the above errors.
> 
> How did you run those commands?
> 
> image

Hi sorry - I ran the check() command!! I can't remember if it's a part of devtools or usethis

**Comment by tdkhanhvu** [comment]
It is `devtools::check()`. I have fixed both issues.

image

**Review by jraza19 — APPROVED** [review]
Looks great!

**Pull request merged**
